---
title: "Final_Project_Alex"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(readxl)
library(scales)
theme_set(theme_minimal())
```

```{r data}
#Eviction data from the Eviction Lab
evictions_state <- read_csv("evictions_state.csv")
states_midpoint <- read_csv("state-midpoints.csv")

states_map <- map_data("state")
county_map <- map_data("county")

evictions_county_org <- read_csv("evictions_county.csv")

evictions_county <- read_csv("evictions_county.csv") %>% 
  separate(col = name, sep = " County", into = c("name", "drop")) %>% 
  select(-drop) %>% 
  mutate(name = str_replace_all(name, "St. ", "St "),
         name = str_replace_all(name, " Parish", "")) %>% 
  left_join(county_centroids,
            by = c("GEOID" = "FIPS")) %>% 
  separate(Latitude, into = c("latitude", "drop1"), 
           sep = "°") %>% 
  separate(Longitude, into = c("longitude", "drop2"), 
           sep = "°") %>% 
  separate(longitude, into = c("drop3", "longitude"), 
           sep = "–") %>% 
  select(-drop1, -drop2, -drop3, -State, -county) %>% 
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude)*-1)

evictions_county$name[evictions_county$name == "LaMoure"] <- "La Moure"
evictions_county$name[evictions_county$name == "DuPage"] <- "Du Page"
evictions_county$name[evictions_county$name == "O'Brien"] <- "OBrien"
evictions_county$name[evictions_county$name == "Ste. Genevieve"] <- "Ste Genevieve"
```

```{r}
evict_rate_map <- evictions_state %>% 
  filter(year == 2016) %>% 
  mutate(name = str_to_lower(name)) %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = name,
               fill = `eviction-rate`)) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map() +
  labs(title = "",
       fill = "") +
  scale_fill_viridis_c() +
  theme(legend.background = element_blank())

  ggplotly(evict_rate_map)
```

```{r}
options(scipen = 9)
evictions_state %>% 
  left_join(states_midpoint,
            by = c("name" = "location")) %>% 
  filter(year == 2016,
         name != "Hawaii") %>% 
  mutate(name = str_to_lower(name)) %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = name,
               fill = population)) +
  geom_point(aes(x = lon, y = lat, size = `eviction-rate`),
             color = "red") +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map() +
  labs(title = "",
       fill = "Population",
       size = "Eviction Rate") +
  scale_fill_viridis_c(labels = comma) +
  theme(legend.background = element_blank(),
        legend.position = "right")
```

```{r}
mydata <- evictions_state[, c(13:24)]
head(mydata)

mydata <- mydata %>% 
  rename(
    `% White` = `pct-white`,
    `% African American` = `pct-af-am` ,
    `% Hispanic` = `pct-hispanic`,
    `% American Indian `= `pct-am-ind`,
    `% Asian` = `pct-asian`,
    `% Pacific Islander` = `pct-nh-pi`,
    `% Multiple` = `pct-multiple`,
    `% Other` = `pct-other`,
    `Eviction Filings` = `eviction-filings`,
    `Evictions` = `evictions`,
    `Eviction Rate` = `eviction-rate`,
    `Eviction Filing Rate` = `eviction-filing-rate`              
  )

cormat <- round(cor(mydata, use = "pairwise.complete.obs"),2)
cormat

library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)
```
```{r}
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  upper_tri <- get_upper_tri(cormat)

melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Heatmap
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
  labs(title = "Correlation Plot",
       y = "",
       x = "") +
 coord_fixed() 
```

```{r}
corrplot2 <- evictions_state[, c(5:12, 21:24)]

corrplot2 <- corrplot2 %>% 
  rename(
    `Population` = `population`,
    `Poverty Rate` = `poverty-rate` ,
    `Renter Occupied Households` = `renter-occupied-households`,
    `% Renter Occupied`= `pct-renter-occupied`,
    `Median Gross Rent` = `median-gross-rent`,
    `Median Household Income` = `median-household-income`,
    `Median Property Value` = `median-property-value`,
    `Rent Burden` = `rent-burden`,
    `Eviction Filings` = `eviction-filings`,
    `Evictions` = `evictions`,
    `Eviction Rate` = `eviction-rate`,
    `Eviction Filing Rate` = `eviction-filing-rate`              
  )

corrplot2 <- round(cor(corrplot2, use = "pairwise.complete.obs"),2)

library(reshape2)
melted_cormat <- melt(corrplot2)

# Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  upper_tri <- get_upper_tri(corrplot2)

melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Heatmap
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 10, hjust = 1))+
  labs(title = "",
       y = "",
       x = "") +
 coord_fixed() 
```

```{r}
plot <- evictions_state %>% 
      left_join(states_midpoint,
                by = c("name" = "location")) %>% 
      filter(year == 2016,
             name != "Alaska",      
             name != "Hawaii") %>% 
      mutate(lwr_name = str_to_lower(name)) %>% 
      ggplot() +
      geom_map(map = states_map,
               aes(map_id = lwr_name,
                   fill = (population),
                   text = paste0(name, paste0(":<br>", format(population , big.mark=","))))) +
      geom_point(aes(x = lon, y = lat, size = `eviction-rate`,
                     text = paste0("Eviction Rate: ", `eviction-rate`)),
                 color = "red") + 
      expand_limits(x = states_map$long, y = states_map$lat) + 
      theme_map() +
      labs(title = "",
           fill = "",
           size = "") +
      scale_fill_viridis_c(labels = comma) +
      theme(legend.background = element_blank(),
            legend.position = "right")
  
  ggplotly(plot, tooltip = c("text"))
```

```{r}
evictions_county %>% 
      filter(year == 2016,
             `parent-location` == "Alabama") %>% 
      mutate(lwr_name = str_to_lower(name)) %>% 
      ggplot() +
      geom_map(map = county_map %>% filter(region == "alabama"),
               aes(map_id = lwr_name,
                   fill = population,
                   text = paste0(name, paste0(": ", format(population , big.mark=","))))) +
      expand_limits(x = county_map$long, y = county_map$lat) + 
      theme_map() +
      labs(title = "",
           fill = "",
           size = "") +
      scale_fill_viridis_c(labels = comma) +
      theme(legend.background = element_blank(),
            legend.position = "right")
```

```{r}
mn_map <- county_map %>% filter(region == "minnesota") %>% select(-region) %>% dplyr::rename(region = subregion)
nd_map <- county_map %>% filter(region == "north dakota") %>% select(-region) %>% dplyr::rename(region = subregion)
map <- county_map %>% filter(region %in% c("missouri", "illinois")) %>% select(-region) %>% dplyr::rename(region = subregion)

county_map %>% select(-region) %>% dplyr::rename(region = subregion)

evictions_county %>% 
  filter(year == 2016,
         `parent-location` == "Minnesota") %>% 
  select (-c("low-flag", "imputed", "subbed")) %>% 
  mutate(lwr_name = str_to_lower(name)) %>% 
  ggplot(aes(fill = population)) +
  geom_map(map = mn_map,
           aes(map_id = lwr_name)) +
  scale_fill_viridis_c(labels = comma) +
  expand_limits(x = mn_map$long, y = mn_map$lat) + 
  theme_map()
```

```{r}
url <- "https://en.wikipedia.org/wiki/User:Michael_J/County_table"
webpage <- read_html(url)

table <- html_nodes(webpage, "table")[[1]] %>% 
  html_table()

county_centroids <- table %>% 
  select(State:`County [2]`, Latitude:Longitude)

names(county_centroids)[names(county_centroids) == "County [2]"] <- "county"

evictions_county_midpoints <- evictions_county %>% 
  left_join(county_centroids,
            by = c("GEOID" = "FIPS")) %>% 
  separate(Latitude, into = c("latitude", "drop1"), 
           sep = "°") %>% 
  separate(Longitude, into = c("longitude", "drop2"), 
           sep = "°") %>% 
  separate(longitude, into = c("drop3", "longitude"), 
           sep = "–") %>% 
  select(-drop1, -drop2, -drop3, -State, -county) %>% 
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude)*-1) %>%
  filter(year == 2016,
         `parent-location` == "Minnesota") %>% 
  select (-c("low-flag", "imputed", "subbed")) %>% 
  mutate(lwr_name = str_to_lower(name)) %>% 
  ggplot(aes(fill = population)) +
  geom_map(map = mn_map,
           aes(map_id = lwr_name)) +
        geom_point(aes(x = longitude, y = latitude, size = `eviction-rate`),
                 color = "red") + 
  scale_fill_viridis_c(labels = comma) +
  expand_limits(x = mn_map$long, y = mn_map$lat) + 
  theme_map()
```

